# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs/pin.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dpu_clk_wiz_0 || ORIG_REF_NAME==top_dpu_clk_wiz_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_gen_clk_0/top_rst_gen_clk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_0 || ORIG_REF_NAME==top_rst_gen_clk_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_gen_clk_dsp_0/top_rst_gen_clk_dsp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_dsp_0 || ORIG_REF_NAME==top_rst_gen_clk_dsp_0} -quiet] -quiet

# IP: bd/top/ip/top_dpu_intc_M_AXI_HP0_FPD_0/top_dpu_intc_M_AXI_HP0_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_HP0_FPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_HP0_FPD_0} -quiet] -quiet

# IP: bd/top/ip/top_dpu_intc_M_AXI_HP1_FPD_0/top_dpu_intc_M_AXI_HP1_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_HP1_FPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_HP1_FPD_0} -quiet] -quiet

# IP: bd/top/ip/top_dpu_intc_M_AXI_LPD_0/top_dpu_intc_M_AXI_LPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_LPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_LPD_0} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_1_0/top_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_1_0 || ORIG_REF_NAME==top_processing_system7_1_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_gen_ghp_0/top_rst_gen_ghp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_gen_ghp_0 || ORIG_REF_NAME==top_rst_gen_ghp_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dpu_eu_0_0/top_dpu_eu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dpu_eu_0_0 || ORIG_REF_NAME==top_dpu_eu_0_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_0/top_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_us_0 || ORIG_REF_NAME==top_auto_us_0} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
