#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : top.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jan 13 23:45:55 PKT 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: top.sh [-help]
# usage: top.sh [-lib_map_path]
# usage: top.sh [-noclean_files]
# usage: top.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'top.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 floating_point_v7_1_9 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_6 processing_system7_vip_v1_0_8 xlconstant_v1_1_6 generic_baseblocks_v2_1_0 fifo_generator_v13_2_5 axi_data_fifo_v2_1_19 axi_register_slice_v2_1_20 axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "top.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_9 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_dpu_0/xci/sfm/fp_exp/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/xci/sfm/fp_exp/sim/fp_exp.vhd" \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/xci/sfm/fp_convert/sim/fp_convert.vhd" \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/xci/sfm/fp_div/sim/fp_div.vhd" \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/xci/sfm/fp_acc/sim/fp_acc.vhd" \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/xci/sfm/fp_add/sim/fp_add.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/top/ipshared/fe10/hdl/dpu_eu_v3_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/top/ip/top_dpu_0/sim/top_dpu_0.v" \
    "$ref_dir/../../../bd/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top/ip/top_rst_gen_clk_0/sim/top_rst_gen_clk_0.vhd" \
    "$ref_dir/../../../bd/top/ip/top_rst_gen_clk_dsp_0/sim/top_rst_gen_clk_dsp_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/dc12/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/top/ip/top_processing_system7_1_0/sim/top_processing_system7_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top/ip/top_rst_gen_ghp_0/sim/top_rst_gen_ghp_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/top/ip/top_xlconstant_0_0/sim/top_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/4fba" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/2d50/hdl" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ipshared/fe10/inc" +incdir+"$ref_dir/../../../../zedboard.srcs/sources_1/bd/top/ip/top_processing_system7_1_0" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/top/ip/top_auto_us_0/sim/top_auto_us_0.v" \
    "$ref_dir/../../../bd/top/sim/top.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.top xil_defaultlib.glbl -o top_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./top_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./top.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/mohammad/Resnet50_ZedBoard_2019_2/pl/prj/zedboard/zedboard.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key top_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc top_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: top.sh [-help]\n\
Usage: top.sh [-lib_map_path]\n\
Usage: top.sh [-reset_run]\n\
Usage: top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
